# Generated by mix mock_pve.gen.feature_matrix — DO NOT EDIT
# Source: pve-openapi v0.2.4
# Generated: 2026-03-27T02:08:54.088340Z
defmodule MockPveApi.FeatureMatrix do
  @moduledoc """
  PVE API feature availability matrix across versions.

  Generated from pve-openapi v0.2.4 feature catalog
  (12 versions, 22 features).

  Features are derived from API endpoint presence in each version's
  OpenAPI spec. See `PveOpenapi.FeatureMatrix.Catalog` for the
  indicator path mappings.

  Regenerate with: `mix mock_pve.gen.feature_matrix`
  """

  @pve_openapi_version "0.2.4"

  @versions ["7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3", "8.4", "9.0", "9.1"]

  @features %{
    "7.0" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :hardware_pci,
      :network_management,
      :pool_management,
      :realm_sync_jobs,
      :sdn,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ],
    "7.1" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :hardware_pci,
      :network_management,
      :pool_management,
      :realm_sync_jobs,
      :sdn,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ],
    "7.2" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :hardware_pci,
      :network_management,
      :pool_management,
      :realm_sync_jobs,
      :sdn,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ],
    "7.3" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :hardware_pci,
      :network_management,
      :pool_management,
      :realm_sync_jobs,
      :sdn,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ],
    "7.4" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :hardware_pci,
      :network_management,
      :pool_management,
      :realm_sync_jobs,
      :sdn,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ],
    "8.0" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :hardware_pci,
      :network_management,
      :pool_management,
      :realm_sync_jobs,
      :resource_mappings,
      :sdn,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ],
    "8.1" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :hardware_pci,
      :network_management,
      :notification_endpoints,
      :notification_system,
      :pool_management,
      :realm_sync_jobs,
      :resource_mappings,
      :sdn,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ],
    "8.2" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :hardware_pci,
      :network_management,
      :notification_endpoints,
      :notification_system,
      :pool_management,
      :realm_sync_jobs,
      :resource_mappings,
      :sdn,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ],
    "8.3" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :hardware_pci,
      :network_management,
      :notification_endpoints,
      :notification_system,
      :pool_management,
      :realm_sync_jobs,
      :resource_mappings,
      :sdn,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ],
    "8.4" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :hardware_pci,
      :network_management,
      :notification_endpoints,
      :notification_system,
      :pool_management,
      :realm_sync_jobs,
      :resource_mappings,
      :sdn,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ],
    "9.0" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :ha_rules,
      :hardware_pci,
      :network_management,
      :notification_endpoints,
      :notification_system,
      :pool_management,
      :realm_sync_jobs,
      :resource_mappings,
      :sdn,
      :sdn_fabrics,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ],
    "9.1" => [
      :acl_management,
      :backup_info,
      :backup_management,
      :ceph_management,
      :cluster_management,
      :container_management,
      :firewall_management,
      :ha_management,
      :ha_rules,
      :hardware_pci,
      :network_management,
      :notification_endpoints,
      :notification_system,
      :pool_management,
      :realm_sync_jobs,
      :resource_mappings,
      :sdn,
      :sdn_fabrics,
      :storage_management,
      :tfa_management,
      :user_management,
      :vm_management
    ]
  }

  @added_in %{
    :acl_management => "7.0",
    :backup_info => "7.0",
    :backup_management => "7.0",
    :ceph_management => "7.0",
    :cluster_management => "7.0",
    :container_management => "7.0",
    :firewall_management => "7.0",
    :ha_management => "7.0",
    :ha_rules => "9.0",
    :hardware_pci => "7.0",
    :network_management => "7.0",
    :notification_endpoints => "8.1",
    :notification_system => "8.1",
    :pool_management => "7.0",
    :realm_sync_jobs => "7.0",
    :resource_mappings => "8.0",
    :sdn => "7.0",
    :sdn_fabrics => "9.0",
    :storage_management => "7.0",
    :tfa_management => "7.0",
    :user_management => "7.0",
    :vm_management => "7.0"
  }

  @doc "The pve-openapi version used to generate this matrix."
  @spec pve_openapi_version() :: String.t()
  def pve_openapi_version, do: @pve_openapi_version

  @doc "All PVE versions in the matrix."
  @spec versions() :: [String.t()]
  def versions, do: @versions

  @doc "Check if a feature is available in a specific PVE version."
  @spec feature_available?(String.t(), atom()) :: boolean()
  def feature_available?(version, feature) do
    case Map.fetch(@features, version) do
      {:ok, features} -> feature in features
      :error -> false
    end
  end

  @doc "Return all features available in a version."
  @spec features_for_version(String.t()) :: [atom()]
  def features_for_version(version) do
    Map.get(@features, version, [])
  end

  @doc "Find the earliest version where a feature became available."
  @spec feature_added_in(atom()) :: String.t() | nil
  def feature_added_in(feature) do
    Map.get(@added_in, feature)
  end

  @doc "Return all features and their availability."
  @spec all_features() :: map()
  def all_features, do: @features
end
