defmodule Mix.Tasks.MockPve.Gen.EndpointMatrix do
  @moduledoc """
  Generates `MockPveApi.EndpointMatrix` from pve-openapi specs.

  Queries `PveOpenapi.VersionMatrix` and produces a committed module at
  `lib/mock_pve_api/endpoint_matrix.ex` with endpoint availability data
  across all known PVE versions.

  Paths are prefixed with `/api2/json` to match mock-pve-api's router convention.

  ## Usage

      mix mock_pve.gen.endpoint_matrix [--force]

  ## Options

    * `--force` - Overwrite the output file even if the pve-openapi version
      has not changed since the last generation.

  ## Prerequisites

  Requires pve-openapi specs to be generated first:

      cd ../pve-openapi && make setup
  """

  use Mix.Task

  @shortdoc "Generate MockPveApi.EndpointMatrix from pve-openapi specs"

  @output_path "lib/mock_pve_api/endpoint_matrix.ex"
  @api_prefix "/api2/json"

  @impl Mix.Task
  def run(args) do
    {opts, _, _} = OptionParser.parse(args, strict: [force: :boolean])
    force? = Keyword.get(opts, :force, false)

    unless Code.ensure_loaded?(PveOpenapi.VersionMatrix) do
      Mix.raise("""
      pve-openapi is not available. Ensure:
        1. {:pve_openapi, path: "../pve-openapi"} is in your deps
        2. You ran `mix deps.get`
        3. Specs exist: run `make setup` in pve-openapi first
      """)
    end

    pve_openapi_version = pve_openapi_version()
    versions = PveOpenapi.versions()

    if Enum.empty?(versions) do
      Mix.raise("No PVE versions found. Run `make setup` in pve-openapi first.")
    end

    output_path = Path.join(File.cwd!(), @output_path)

    if !force? && File.exists?(output_path) do
      case check_version_header(output_path, pve_openapi_version) do
        :same ->
          Mix.shell().info(
            "EndpointMatrix is up-to-date (pve-openapi v#{pve_openapi_version}). Use --force to regenerate."
          )

          :ok

        :different ->
          Mix.shell().info("pve-openapi version changed, regenerating...")
          generate(versions, pve_openapi_version, output_path)

        :missing ->
          generate(versions, pve_openapi_version, output_path)
      end
    else
      generate(versions, pve_openapi_version, output_path)
    end
  end

  defp generate(versions, pve_openapi_version, output_path) do
    matrix =
      for version <- versions, into: %{} do
        endpoints =
          PveOpenapi.VersionMatrix.endpoints_for_version(version)
          |> MapSet.new(fn {path, method} -> {@api_prefix <> path, method} end)

        {version, endpoints}
      end

    total_endpoints =
      matrix
      |> Map.values()
      |> Enum.reduce(MapSet.new(), &MapSet.union/2)
      |> MapSet.size()

    first_version = List.first(versions)
    last_version = List.last(versions)

    content = render_module(versions, matrix, pve_openapi_version, first_version, last_version)

    output_path
    |> Path.dirname()
    |> File.mkdir_p!()

    File.write!(output_path, content)

    Mix.shell().info("""
    Generated #{output_path}
      pve-openapi: v#{pve_openapi_version}
      versions:    #{length(versions)} (#{first_version}–#{last_version})
      endpoints:   #{total_endpoints} unique (paths prefixed with #{@api_prefix})
    """)
  end

  defp render_module(versions, matrix, pve_openapi_version, first_version, last_version) do
    timestamp = DateTime.utc_now() |> DateTime.to_iso8601()

    versions_literal = inspect(versions, limit: :infinity)

    matrix_entries =
      Enum.map_join(versions, ",\n", fn version ->
        endpoints = Map.fetch!(matrix, version)

        tuples =
          endpoints
          |> MapSet.to_list()
          |> Enum.sort()
          |> Enum.map_join(", ", fn {path, method} -> "{#{inspect(path)}, :#{method}}" end)

        "    #{inspect(version)} => MapSet.new([#{tuples}])"
      end)

    """
    # Generated by mix mock_pve.gen.endpoint_matrix — DO NOT EDIT
    # Source: pve-openapi v#{pve_openapi_version}
    # Generated: #{timestamp}
    defmodule MockPveApi.EndpointMatrix do
      @moduledoc \"""
      PVE API endpoint availability matrix across versions.

      Generated from pve-openapi v#{pve_openapi_version} specs
      (#{length(versions)} versions, #{first_version}–#{last_version}).
      Paths are prefixed with `/api2/json` to match the mock server router.

      Regenerate with: `mix mock_pve.gen.endpoint_matrix`
      \"""

      @pve_openapi_version #{inspect(pve_openapi_version)}

      @versions #{versions_literal}

      @matrix %{
    #{matrix_entries}
      }

      @dialyzer {:no_opaque, available?: 3, endpoints_for: 1, versions_for: 2, added_in: 2}

      @doc "The pve-openapi version used to generate this matrix."
      @spec pve_openapi_version() :: String.t()
      def pve_openapi_version(), do: @pve_openapi_version

      @doc "All PVE versions in the matrix."
      @spec versions() :: [String.t()]
      def versions(), do: @versions

      @doc "Check if an endpoint is available in a specific PVE version."
      @spec available?(String.t(), atom(), String.t()) :: boolean()
      def available?(path, method, version) do
        case Map.fetch(@matrix, version) do
          {:ok, endpoints} -> MapSet.member?(endpoints, {path, method})
          :error -> false
        end
      end

      @doc "Find the earliest version where an endpoint was added."
      @spec added_in(String.t(), atom()) :: String.t() | nil
      def added_in(path, method) do
        Enum.find(@versions, fn version ->
          available?(path, method, version)
        end)
      end

      @doc "Return all versions where an endpoint is available."
      @spec versions_for(String.t(), atom()) :: [String.t()]
      def versions_for(path, method) do
        Enum.filter(@versions, fn version ->
          available?(path, method, version)
        end)
      end

      @doc "Return all {path, method} tuples available in a version."
      @spec endpoints_for(String.t()) :: MapSet.t()
      def endpoints_for(version) do
        Map.get(@matrix, version, MapSet.new())
      end
    end
    """
  end

  defp pve_openapi_version() do
    case :application.get_key(:pve_openapi, :vsn) do
      {:ok, vsn} -> List.to_string(vsn)
      :undefined -> "unknown"
    end
  end

  defp check_version_header(path, current_version) do
    case File.read(path) do
      {:ok, content} ->
        if String.contains?(content, "pve-openapi v#{current_version}") do
          :same
        else
          :different
        end

      {:error, _} ->
        :missing
    end
  end
end
