defmodule Mix.Tasks.MockPve.Gen.FeatureMatrix do
  @moduledoc """
  Generates `MockPveApi.FeatureMatrix` from pve-openapi feature catalog.

  Queries `PveOpenapi.FeatureMatrix` and produces a committed module at
  `lib/mock_pve_api/feature_matrix.ex` with feature availability data
  across all known PVE versions.

  ## Usage

      mix mock_pve.gen.feature_matrix [--force]

  ## Options

    * `--force` - Overwrite the output file even if the pve-openapi version
      has not changed since the last generation.

  ## Prerequisites

  Requires pve-openapi specs to be generated first:

      cd ../pve-openapi && make setup
  """

  use Mix.Task

  @shortdoc "Generate MockPveApi.FeatureMatrix from pve-openapi feature catalog"

  @output_path "lib/mock_pve_api/feature_matrix.ex"

  @impl Mix.Task
  def run(args) do
    {opts, _, _} = OptionParser.parse(args, strict: [force: :boolean])
    force? = Keyword.get(opts, :force, false)

    unless Code.ensure_loaded?(PveOpenapi.FeatureMatrix) do
      Mix.raise("""
      pve-openapi is not available. Ensure:
        1. {:pve_openapi, path: "../pve-openapi"} is in your deps
        2. You ran `mix deps.get`
        3. Specs exist: run `make setup` in pve-openapi first
      """)
    end

    pve_openapi_version = pve_openapi_version()
    output_path = Path.join(File.cwd!(), @output_path)

    if !force? && File.exists?(output_path) do
      case check_version_header(output_path, pve_openapi_version) do
        :same ->
          Mix.shell().info(
            "FeatureMatrix is up-to-date (pve-openapi v#{pve_openapi_version}). Use --force to regenerate."
          )

          :ok

        :different ->
          Mix.shell().info("pve-openapi version changed, regenerating...")
          generate(pve_openapi_version, output_path)

        :missing ->
          generate(pve_openapi_version, output_path)
      end
    else
      generate(pve_openapi_version, output_path)
    end
  end

  defp generate(pve_openapi_version, output_path) do
    versions = PveOpenapi.versions()
    all_features = PveOpenapi.FeatureMatrix.all_features()

    # Build version -> [feature_atom] map
    features_by_version =
      for version <- versions, into: %{} do
        features =
          all_features
          |> Enum.filter(fn {_feature, available_versions} -> version in available_versions end)
          |> Enum.map(fn {feature, _} -> feature end)
          |> Enum.sort()

        {version, features}
      end

    total_features = map_size(all_features)

    content = render_module(versions, features_by_version, all_features, pve_openapi_version)

    output_path
    |> Path.dirname()
    |> File.mkdir_p!()

    File.write!(output_path, content)

    Mix.shell().info("""
    Generated #{output_path}
      pve-openapi: v#{pve_openapi_version}
      versions:    #{length(versions)} (#{List.first(versions)}–#{List.last(versions)})
      features:    #{total_features}
    """)
  end

  defp render_module(versions, features_by_version, all_features, pve_openapi_version) do
    timestamp = DateTime.utc_now() |> DateTime.to_iso8601()
    versions_literal = inspect(versions, limit: :infinity)

    matrix_entries =
      Enum.map_join(versions, ",\n", fn version ->
        features = Map.fetch!(features_by_version, version)
        features_literal = inspect(features, limit: :infinity)
        "    #{inspect(version)} => #{features_literal}"
      end)

    added_in_entries =
      all_features
      |> Enum.sort()
      |> Enum.map_join(",\n", fn {feature, available_versions} ->
        first = List.first(available_versions)
        "    #{inspect(feature)} => #{inspect(first)}"
      end)

    """
    # Generated by mix mock_pve.gen.feature_matrix — DO NOT EDIT
    # Source: pve-openapi v#{pve_openapi_version}
    # Generated: #{timestamp}
    defmodule MockPveApi.FeatureMatrix do
      @moduledoc \"""
      PVE API feature availability matrix across versions.

      Generated from pve-openapi v#{pve_openapi_version} feature catalog
      (#{length(versions)} versions, #{map_size(all_features)} features).

      Features are derived from API endpoint presence in each version's
      OpenAPI spec. See `PveOpenapi.FeatureMatrix.Catalog` for the
      indicator path mappings.

      Regenerate with: `mix mock_pve.gen.feature_matrix`
      \"""

      @pve_openapi_version #{inspect(pve_openapi_version)}

      @versions #{versions_literal}

      @features %{
    #{matrix_entries}
      }

      @added_in %{
    #{added_in_entries}
      }

      @doc "The pve-openapi version used to generate this matrix."
      @spec pve_openapi_version() :: String.t()
      def pve_openapi_version, do: @pve_openapi_version

      @doc "All PVE versions in the matrix."
      @spec versions() :: [String.t()]
      def versions, do: @versions

      @doc "Check if a feature is available in a specific PVE version."
      @spec feature_available?(String.t(), atom()) :: boolean()
      def feature_available?(version, feature) do
        case Map.fetch(@features, version) do
          {:ok, features} -> feature in features
          :error -> false
        end
      end

      @doc "Return all features available in a version."
      @spec features_for_version(String.t()) :: [atom()]
      def features_for_version(version) do
        Map.get(@features, version, [])
      end

      @doc "Find the earliest version where a feature became available."
      @spec feature_added_in(atom()) :: String.t() | nil
      def feature_added_in(feature) do
        Map.get(@added_in, feature)
      end

      @doc "Return all features and their availability."
      @spec all_features() :: map()
      def all_features, do: @features
    end
    """
  end

  defp pve_openapi_version do
    case :application.get_key(:pve_openapi, :vsn) do
      {:ok, vsn} -> List.to_string(vsn)
      :undefined -> "unknown"
    end
  end

  defp check_version_header(path, current_version) do
    case File.read(path) do
      {:ok, content} ->
        if String.contains?(content, "pve-openapi v#{current_version}") do
          :same
        else
          :different
        end

      {:error, _} ->
        :missing
    end
  end
end
